MiniProject-master/MiniProject-master/TravelGuide/TravelGuide/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from testapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('testapp/',include('testapp.urls')),
    path('special/',views.special,name='special'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='testapp/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='testapp/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='testapp/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='testapp/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

MiniProject-master/MiniProject-master/TravelGuide/testapp/urls.py
from django.conf.urls import url
from testapp import views
from django.views.generic import RedirectView
from django.urls import path

app_name='testapp'
urlpatterns=[

     url(r'^tourist/',views.Tourist_registration,name='Tourist_registration'),
     url(r'^guide/',views.Guide_registration,name='Guide_registration'),
     url(r'^tourist_login/',views.tourist_login,name='tourist_login'),
     url(r'^tourist_logout/',views.tourist_logout,name='tourist_logout'),
     url(r'^guide_Login/', views.guide_login, name='guide_login'),
     url(r'^guide_logout/', views.guide_logout, name='guide_logout'),
     url(r'^tourist_language_view/',views.tourist_language_view,name='tourist_language_view'),
     url(r'^guide_booking_view/',views.guide_booking_view,name='guide_booking_view'),
     url(r'^favicon\.ico$', RedirectView.as_view(url='/static/Images/favicon.ico')),
     url(r'^hyderabad1/',views.Hyderabad_view1,name='Hyderabad_view1'),
     url(r'^hyderabad2/',views.Hyderabad_view2,name='Hyderabad_view2'),
     url(r'^hyderabad3/',views.Hyderabad_view3,name='Hyderabad_view3'),
     url(r'^warangal1/',views.Warangal_view1,name='Warangal_view1'),
     url(r'^vizag1/',views.Vizag_view1,name='Vizag_view1'),
     url(r'^vijayawada1/',views.Vijayawada_view1,name='Vijayawada_view1'),
     url(r'^adilabad1/',views.Adilabad_view1,name='Adilabad_view1'),
     url(r'^warangal2/', views.Warangal_view2, name='Warangal_view2'),
     url(r'^vizag2/', views.Vizag_view2, name='Vizag_view2'),
     url(r'^vijayawada2/', views.Vijayawada_view2, name='Vijayawada_view2'),
     url(r'^adilabad2/', views.Adilabad_view2, name='Adilabad_view2'),
     url(r'^warangal3/', views.Warangal_view3, name='Warangal_view3'),
     url(r'^vizag3/', views.Vizag_view3, name='Vizag_view3'),
     url(r'^vijayawada3/', views.Vijayawada_view3, name='Vijayawada_view3'),
     url(r'^guide_book/',views.guide_booking_view,name='guide_booking_view'),
     path('display_view/', views.display_book_view, name='display_book_view'),

]

MiniProject-master/MiniProject-master/TravelGuide/testapp/models.py
from django.db import models
from django.contrib.auth.models import (AbstractUser,User)
from multiselectfield import MultiSelectField
# Create your models here.
class User(AbstractUser):
    is_tourist=models.BooleanField(default=False)
    is_guide=models.BooleanField(default=False)
    email = models.EmailField(unique=True)


class Tourist_Registration(models.Model):

    first_name=models.CharField(max_length=10,blank=False)
    last_name=models.CharField(max_length=10,blank=False)
    user_name=models.CharField(max_length=12,blank=False,unique=True)
    email_id=models.EmailField(max_length=255,blank=False)
    pass_word=models.CharField(max_length=20,blank=False)
    language=models.CharField(max_length=10,blank=False)
    gender=models.CharField(max_length=7,blank=False)
    phone_number = models.CharField(max_length=10, default="",blank=False,unique=True)
    age = models.CharField(max_length=2, blank=True)




class Guide_Registration(models.Model):

    first_name = models.CharField(max_length=10, blank=False)
    last_name=models.CharField(max_length=10,blank=False)
    user_name=models.CharField(max_length=12,blank=False,unique=True)
    email_id=models.EmailField(max_length=255,blank=False)
    pass_word=models.CharField(max_length=20,blank=False)
    gender= models.CharField(max_length=7,blank=True)
    native_place=models.CharField(max_length=25,blank=True)
    phone_number = models.CharField(max_length=10, default="", blank=False, unique=True)
    age = models.CharField(max_length=2, blank=False)
    Address=models.CharField(blank=False,max_length=50)


class language_Selection(models.Model):
    user=models.ForeignKey(Guide_Registration,on_delete=models.CASCADE)
    #user = models.CharField(max_length=25,null=True, blank=True, unique=True)
    languages_Know=(
                      ('Telugu','Telugu'),('Hindi','Hindi'),('English','English'),('Spanish','Spanish'),

                    )
    languages_select = MultiSelectField(choices=languages_Know,max_choices=4,max_length=100)



class Guide_Booking_Model(models.Model):
    tourist_username=models.ForeignKey(Tourist_Registration,on_delete=models.CASCADE,blank=True,null=True)
    guide_username=models.ForeignKey(Guide_Registration,on_delete=models.CASCADE)
    date_field=models.DateField(max_length=20)

    class Meta:
        unique_together = ('guide_username', 'date_field',)




MiniProject-master/MiniProject-master/TravelGuide/testapp/forms.py
from django import forms
from testapp.models import Tourist_Registration,Guide_Registration,language_Selection
class Tourist(forms.ModelForm):
    #password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=Tourist_Registration
        fields='__all__'


class Guide(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=Guide_Registration
        fields='__all__'

class Language_Form(forms.ModelForm):
    class Meta():
        model=language_Selection
        fields = '__all__'

MiniProject-master/MiniProject-master/TravelGuide/testapp/views.py
from django.shortcuts import render
from testapp.forms import Tourist,Guide,Language_Form
from testapp.models import User,language_Selection
from testapp.models import Tourist_Registration,Guide_Registration,Guide_Booking_Model
from django.contrib.auth.hashers import make_password
# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
import smtplib
import csv
import email
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# Create your views here.
def Hyderabad_view1(request):
    return render(request,'testapp/hyderabad/hyderabad1.html')
def Warangal_view1(request):
    return render(request,'testapp/warangal/warangal.html')
def Vijayawada_view1(request):
    return render(request,'testapp/vijaywada/vijayawada1.html')
def Vizag_view1(request):
    return render(request,'testapp/vizag/vizag.html')
def Adilabad_view1(request):
    return render(request,'testapp/adilabad/adilabad1.html')
def Hyderabad_view2(request):
    return render(request,'testapp/hyderabad/hyderabad2.html')
def Warangal_view2(request):
    return render(request,'testapp/warangal/warangal2.html')
def Vijayawada_view2(request):
    return render(request,'testapp/vijaywada/vijayawada2.html')
def Vizag_view2(request):
    return render(request,'testapp/vizag/vizag2.html')
def Adilabad_view2(request):
    return render(request,'testapp/adilabad/adilabad2.html')
def Hyderabad_view3(request):
    return render(request,'testapp/hyderabad/hyderabad3.html')
def Warangal_view3(request):
    return render(request,'testapp/warangal/warangal3.html')
def Vijayawada_view3(request):
    return render(request,'testapp/vijaywada/vijayawada3.html')
def Vizag_view3(request):
    return render(request,'testapp/vizag/vizag3.html')

def index(request):

    return render(request,'testapp/index.html')

def tourist_index(request):
    return render(request,'testapp/tourist_details.html')

def special(request) :
    return HttpResponse("you are logged in,Nice!")

def tourist_logout(request):
    logout(request)
    return render(request,'testapp/index.html')

def guide_logout(request):
    logout(request)
    return render(request,'testapp/index.html')
def Tourist_registration(request):
    registered=False
    if request.method=="POST":
            first_name = request.POST.get('Firstname')
            print(first_name)
            last_name=request.POST.get('Lastname')
            user_name=request.POST.get('Username')
            email_id=request.POST.get('Email')
            pass_word = request.POST.get('Password')
            language=request.POST.get('language')
            gender=request.POST.get('gender')
            age=request.POST.get('age')
            phone_number=request.POST.get('Phonenumber')
            enc_password=make_password(pass_word)
            user=User(username=user_name,password=enc_password)
            user.is_tourist=True
            user.is_guide=False
            user.email=email_id
            try:
                user.save()
                form=Tourist_Registration(first_name=first_name,last_name=last_name,user_name=user_name,email_id=email_id,pass_word=pass_word,language=language,gender=gender,age=age,phone_number=phone_number)
                t=form.save()
            except:
                messages.warning(request, 'username or Email already exists Please Try again with New one')
                return HttpResponseRedirect('testapp/index.html')

            registered = True
            messages.success(request, 'successfully Registered Please Login!')
            return HttpResponseRedirect('testapp/index.html')
    else:
        return render(request,'testapp/index.html')

def Guide_registration(request):
    registered=False
    if request.method=="POST":

        first_name = request.POST.get('Firstname')
        print(first_name)
        last_name = request.POST.get('Lastname')
        user_name = request.POST.get('Username')
        email_id = request.POST.get('Email')
        pass_word = request.POST.get('Password')
        gender = request.POST.get('gender')
        age = request.POST.get('age')
        phone_number = request.POST.get('Phonenumber')
        native_place=request.POST.get('place')
        Address=request.POST.get('address')
        enc_password = make_password(pass_word)
        user = User(username=user_name, password=enc_password)
        user.is_tourist = False
        user.is_guide = True
        user.email=email_id
        try:
            user.save()
            form=Guide_Registration(first_name=first_name,last_name=last_name,user_name=user_name,email_id=email_id,pass_word=pass_word,gender=gender,age=age,phone_number=phone_number,native_place=native_place,Address=Address)
            t=form.save()

        except:
                messages.warning(request,'username or Email already exists Please Try again with new')
                return HttpResponseRedirect("testapp/index.html")
        registered = True
        messages.success(request, 'successfully Registered Please Login to Select the Languages you Known!')
        return HttpResponseRedirect("testapp/index.html")

    else:
       return render(request,'testapp/index.html')



def tourist_login(request):

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)
        if user and user.is_tourist==True:
            if user.is_active:
                login(request,user)
                return render(request,"testapp/tourist_details.html",{'user':user})
            else:
                return render(request,'testapp/index.html')

        else:
            messages.warning(request, 'Invalid credentials!')
            return  HttpResponseRedirect("testapp/index.html")

    else:
        return render(request,'testapp/index.html',{})


def guide_login(request):

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password,is_guide=True,is_tourist=False)
        if user and user.is_guide==True:
            if user.is_active:
                login(request,user)
                return render(request,"testapp/guide_details.html",{'user':user})
            else:
                return render(request,"testapp/index.html")

        else:
            messages.warning(request,'Please Enter Correct details!')
            return HttpResponseRedirect("testapp/index.html")
    else:
        return render(request,'testapp/index.html',{})

def tourist_language_view(request):
    if request.method=='POST':
        #guide_obj=User.objects.get(username=request.user)
        guide_obj = Guide_Registration.objects.get(user_name=request.user)
        #print(guide_obj)
        try:
              check= language_Selection.objects.get(user=guide_obj)
        except:
            check=None
        if check is None:
            ob1=language_Selection(user=guide_obj,languages_select=request.POST.getlist('languages_select'))
            #print(guide_obj,ob1.languages_select)
            #print(request.POST.getlist('languages_select'))
            ob1.save()
        else:
            list_of_lang=check.languages_select
            check.languages_select=request.POST.getlist('languages_select')
            #selection=form.cleaned_data.get('languages_select')
            check.save()
        return render(request,'testapp/guide_details.html')
    else:
        return render(request,'testapp/language_add.html')

def guide_booking_view(request):
    if request.method =='POST':
        date_value=(request.POST.get('date'))
        place_value=request.POST.get('place')
        gender_value = request.POST.get('gender')
        user_value=request.user
        language_value=request.POST.get('language')
        print(date_value,place_value,gender_value,language_value)
        try:
            guide_obj=Guide_Registration.objects.exclude(guide_booking_model__date_field=date_value).filter(native_place=place_value,gender=gender_value)
            query_set_list=[]
            print(guide_obj)
            for query_obj in guide_obj:
                try:
                   p=language_Selection.objects.get(user=query_obj.id)
                   checking=language_value in p.languages_select
                   if(checking==True):
                        query_set_list.append(query_obj)
                except:
                    pass
            print(query_set_list)
            return render(request,'testapp/display_available.html',{'query_set_list':query_set_list,'date_value':date_value})
        except:

            return render(request, 'testapp/display_available.html', {'query_set_list': query_set_list,'date_value':date_value})

    else:
        return render(request,'testapp/guide_book.html')


def display_book_view(request):
    print(request.user)
    guideid = request.GET['id']
    tourist_name=(request.GET['id1'])
    tourist_obj=Tourist_Registration.objects.get(user_name=tourist_name)
    date_value=request.GET['date_value']
    guide_obj=Guide_Registration.objects.get(id=guideid)
    print(guide_obj)
    print(tourist_obj)
    book_obj = Guide_Booking_Model(tourist_username=tourist_obj, guide_username=guide_obj, date_field=date_value)
    book_obj.save()

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/Guide_page.html
{% extends "testapp/base.html" %}
{% block body_block %}

   <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>
        <div class="form-group">
            {% if messages %}
              <ul class="messages">
                  {% for message in messages %}
                      <div class="alert alert-info">{{ message }} </div>
                  {% endfor %}
              </ul>
            {% endif %}
        </div>

        <form method="post" action="{% url 'testapp:guide_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="username">

          <label for="password">password:</label>
          <input type="password" name="password" placeholder="password">

          <input type="submit" name="" value="Login">

        </form>
    </br>

        If you don't already have an account,<a href="/testapp/guide/"><strong>register</strong></a> first</br>
        <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot Password?</a>
        </small>

    </div>
  </div>

{% endblock %}

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/display_available.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>
<body>

    <h2 align="center">Available Guides on Selected Day</h2>
    {% for post in query_set_list %}
     <div class="container">
      <div class="jumbotron" align="center">
       <h3>User Name:{{ post.user_name }}</h3>
       <h3>email_id: {{ post.email_id }}</h3>
       <h3>gender:{{ post.gender }}</h3>
       <h3>Phone Number:{{ post.phone_number }}</h3>
       <h3>Native_place:{{ post.native_place }}</h3>
       <h3>Age:{{ post.age }}</h3>
       <h3>Address:{{ post.Address }}</h3>

          <a class="btn btn-info" href="{% url 'testapp:display_book_view' %}?id={{post.id}}&id1={{request.user}}&date_value={{date_value}}">BOOK</a>
      </div>
     </div>
    {% endfor %}
</body>
</html>

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/guide_book.html

<!DOCTYPE html>
<html>
 <head>
      <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
   </head>
 <body style="background-color:cornsilk;">
     <div class="container">
         <div class="jumbotron">
           <h2>Enter the details to book the Guide</h2>

            <form method="post" action="{% url 'testapp:guide_booking_view' %}">
                    {% csrf_token %}
                 <h3><label for="place">Place Selection:</label> &emsp;
                 <select name="place">
                       <option value="Hyderabad">Hyderabad</option>
                       <option value="Warangal">Warangal</option>
                       <option value="Adilabad">Adilabad</option>
                       <option value="Vizag">Vizag</option>
                       <option value="Vijayawada">Vijayawada</option>
                 </select></h3><br/>
                 <h3><label for="language">language Selection:</label>
                 <select name="language">
                       <option value="Telugu">Telugu</option>
                       <option value="Hindi">Hindi</option>
                       <option value="English">English</option>
                       <option value="Spanish">Spanish</option>
                 </select></h3><br/>



                     <h3> <label for="gender_select">Gender Selection:</label> &emsp;
                      <input type="radio" name="gender" value="Male" checked> Male &emsp;
                         <input type="radio" name="gender" value="Female"> Female &emsp;
                      <input type="radio" name="gender" value="Other"> Others<br></h3>
                 <br/>

                  <div class="form-group"> <!-- Date input -->
                       <label class="control-label" for="date">Date</label>
                       <input class="form-control" id="date" name="date" placeholder="yyyy-mm-dd" type="text" required/>
                    </div>

                     <input type="submit" class='btn btn-primary' value="submit">

            </form>

         </div>
     </div>
   <script>
    $(document).ready(function(){
      var date_input=$('input[name="date"]'); //our date input has the name "date"
      var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
      var options={
        format: 'yyyy-mm-dd',
        container: container,
        todayHighlight: true,
        autoclose: true,
      };
      date_input.datepicker(options);
    })
</script>

    </body>
</html>



MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/guide_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Title</title>
</head>
  <body style="background-color:chartreuse;">

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Welcome {{user.username}}</a>&emsp;&emsp;&emsp;&emsp;
    </div>
    <ul class="nav navbar-nav">

      <li><a href="{% url 'testapp:tourist_language_view'   %}">Add Languages</a></li>&emsp;&emsp;&emsp;&emsp;&emsp;
      <li><a href="{% url 'testapp:guide_logout' %}">Logout</a></li>
    </ul>



  </body>
</html>

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/language_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
     <body>
      <div class="container">
       <div class="jumbotron">

       <div class="form-group">
           <label for="sel1">Select languages you Know:</label>
          <form method="POST" action="{% url 'testapp:tourist_language_view' %}">
          <select multiple="multiple"  name="languages_select" id="services" size="4" class="form-control">

              <option value="Telugu">Telugu</option>
              <option value="Hindi">Hindi</option>
              <option value="English">Engilsh</option>
              <option value="Spanish">Spanish</option>

          </select>
                 {% csrf_token %}
                 <input type="submit" class='btn btn-primary' value="submit">
          </form>
       </div>
       </div>
      </div>
     </body>
</html>

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/password_reset.html

{% load crispy_forms_tags %}
<html>
<head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/D2C22773-14A6-D84B-A349-93E419AD1B81/main.js" charset="UTF-8"></script><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<style>
.alert{
  background-color:skyblue;
  width:70%;
  padding:15px;
  margin:70px 30px;
  display:inline-block;
  border:5px solid #ccc;
  border-radius:5px;
  box-sizing: border-box;
}
</style>

</head>
<body>

   <div class="alert">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
   </div>
</body>
</html>

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/password_reset_complete.html
<html>
<head>

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/D2C22773-14A6-D84B-A349-93E419AD1B81/main.js" charset="UTF-8"></script><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<style>
.alert{
	background-color:green;
	width:70%;
	padding:15px;
	margin:70px 30px;
	display:inline-block;
	border:5px solid #ccc;
	border-radius:5px;
	box-sizing: border-box;
}
</style>

</head>
<body >

    <div class="alert">
        Your password has been set.
    </div>
    <a href="{% url 'index' %}">Sign In Here</a>
</body>
</html>

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/password_reset_confirm.html
{% load crispy_forms_tags %}
<html>
<head>

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/D2C22773-14A6-D84B-A349-93E419AD1B81/main.js" charset="UTF-8"></script><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<style>
.alert{
  background-color:green;
  width:70%;
  padding:15px;
  margin:70px 30px;
  display:inline-block;
  border:5px solid #ccc;
  border-radius:5px;
  box-sizing: border-box;
}
</style>


</head>
<body>
    <div class="alert">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
</body>
</html>

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/password_reset_done.html
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/D2C22773-14A6-D84B-A349-93E419AD1B81/main.js" charset="UTF-8"></script><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>
.alert{
	background-color:green;
	width:70%;
	padding:15px;
	margin:70px 30px;
	display:inline-block;
	border:5px solid #ccc;
	border-radius:5px;
	box-sizing: border-box;
}
</style>



</head>
<body >

    <div class="alert">
        An email has been sent with instructions to reset your password
    </div>
</body>
</html>

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/tourist_details.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body style="background-color:chartreuse;">


            <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Welcome {{user.username}}</a>
    </div>
    <ul class="nav navbar-nav">

      <li><a href="{% url 'testapp:guide_booking_view'   %}">Book Guide</a></li>
      <li><a href="{% url 'testapp:tourist_logout' %}">Logout</a></li>
    </ul>
  </div>
            </nav>
  </body>
</html>