MiniProject-master/MiniProject-master/TravelGuide/TravelGuide/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from testapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('testapp/',include('testapp.urls')),
    path('special/',views.special,name='special'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='testapp/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='testapp/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='testapp/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='testapp/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

MiniProject-master/MiniProject-master/TravelGuide/testapp/urls.py
from django.conf.urls import url
from testapp import views
from django.views.generic import RedirectView
from django.urls import path

app_name='testapp'
urlpatterns=[

     url(r'^tourist/',views.Tourist_registration,name='Tourist_registration'),
     url(r'^guide/',views.Guide_registration,name='Guide_registration'),
     url(r'^tourist_login/',views.tourist_login,name='tourist_login'),
     url(r'^tourist_logout/',views.tourist_logout,name='tourist_logout'),
     url(r'^guide_Login/', views.guide_login, name='guide_login'),
     url(r'^guide_logout/', views.guide_logout, name='guide_logout'),
     url(r'^tourist_language_view/',views.tourist_language_view,name='tourist_language_view'),
     url(r'^guide_booking_view/',views.guide_booking_view,name='guide_booking_view'),
     url(r'^favicon\.ico$', RedirectView.as_view(url='/static/Images/favicon.ico')),
     url(r'^hyderabad1/',views.Hyderabad_view1,name='Hyderabad_view1'),
     url(r'^hyderabad2/',views.Hyderabad_view2,name='Hyderabad_view2'),
     url(r'^hyderabad3/',views.Hyderabad_view3,name='Hyderabad_view3'),
     url(r'^warangal1/',views.Warangal_view1,name='Warangal_view1'),
     url(r'^vizag1/',views.Vizag_view1,name='Vizag_view1'),
     url(r'^vijayawada1/',views.Vijayawada_view1,name='Vijayawada_view1'),
     url(r'^adilabad1/',views.Adilabad_view1,name='Adilabad_view1'),
     url(r'^warangal2/', views.Warangal_view2, name='Warangal_view2'),
     url(r'^vizag2/', views.Vizag_view2, name='Vizag_view2'),
     url(r'^vijayawada2/', views.Vijayawada_view2, name='Vijayawada_view2'),
     url(r'^adilabad2/', views.Adilabad_view2, name='Adilabad_view2'),
     url(r'^warangal3/', views.Warangal_view3, name='Warangal_view3'),
     url(r'^vizag3/', views.Vizag_view3, name='Vizag_view3'),
     url(r'^vijayawada3/', views.Vijayawada_view3, name='Vijayawada_view3'),
     url(r'^guide_book/',views.guide_booking_view,name='guide_booking_view'),
     path('display_view/', views.display_book_view, name='display_book_view'),

]

MiniProject-master/MiniProject-master/TravelGuide/testapp/models.py
from django.db import models
from django.contrib.auth.models import (AbstractUser,User)
from multiselectfield import MultiSelectField
# Create your models here.
class User(AbstractUser):
    is_tourist=models.BooleanField(default=False)
    is_guide=models.BooleanField(default=False)
    email = models.EmailField(unique=True)


class Tourist_Registration(models.Model):

    first_name=models.CharField(max_length=10,blank=False)
    last_name=models.CharField(max_length=10,blank=False)
    user_name=models.CharField(max_length=12,blank=False,unique=True)
    email_id=models.EmailField(max_length=255,blank=False)
    pass_word=models.CharField(max_length=20,blank=False)
    language=models.CharField(max_length=10,blank=False)
    gender=models.CharField(max_length=7,blank=False)
    phone_number = models.CharField(max_length=10, default="",blank=False,unique=True)
    age = models.CharField(max_length=2, blank=True)




class Guide_Registration(models.Model):

    first_name = models.CharField(max_length=10, blank=False)
    last_name=models.CharField(max_length=10,blank=False)
    user_name=models.CharField(max_length=12,blank=False,unique=True)
    email_id=models.EmailField(max_length=255,blank=False)
    pass_word=models.CharField(max_length=20,blank=False)
    gender= models.CharField(max_length=7,blank=True)
    native_place=models.CharField(max_length=25,blank=True)
    phone_number = models.CharField(max_length=10, default="", blank=False, unique=True)
    age = models.CharField(max_length=2, blank=False)
    Address=models.CharField(blank=False,max_length=50)


class language_Selection(models.Model):
    user=models.ForeignKey(Guide_Registration,on_delete=models.CASCADE)
    #user = models.CharField(max_length=25,null=True, blank=True, unique=True)
    languages_Know=(
                      ('Telugu','Telugu'),('Hindi','Hindi'),('English','English'),('Spanish','Spanish'),

                    )
    languages_select = MultiSelectField(choices=languages_Know,max_choices=4,max_length=100)



class Guide_Booking_Model(models.Model):
    tourist_username=models.ForeignKey(Tourist_Registration,on_delete=models.CASCADE,blank=True,null=True)
    guide_username=models.ForeignKey(Guide_Registration,on_delete=models.CASCADE)
    date_field=models.DateField(max_length=20)

    class Meta:
        unique_together = ('guide_username', 'date_field',)




MiniProject-master/MiniProject-master/TravelGuide/testapp/forms.py
from django import forms
from testapp.models import Tourist_Registration,Guide_Registration,language_Selection
class Tourist(forms.ModelForm):
    #password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=Tourist_Registration
        fields='__all__'


class Guide(forms.ModelForm):
    #password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=Guide_Registration
        fields='__all__'

class Language_Form(forms.ModelForm):
    class Meta():
        model=language_Selection
        fields = '__all__'

MiniProject-master/MiniProject-master/TravelGuide/testapp/views.py
from django.shortcuts import render
from testapp.forms import Tourist,Guide,Language_Form
from testapp.models import User,language_Selection
from testapp.models import Tourist_Registration,Guide_Registration,Guide_Booking_Model
from django.contrib.auth.hashers import make_password
# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
import smtplib
import csv
import email
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# Create your views here.
def Hyderabad_view1(request):
    return render(request,'testapp/hyderabad/hyderabad1.html')
def Warangal_view1(request):
    return render(request,'testapp/warangal/warangal.html')
def Vijayawada_view1(request):
    return render(request,'testapp/vijaywada/vijayawada1.html')
def Vizag_view1(request):
    return render(request,'testapp/vizag/vizag.html')
def Adilabad_view1(request):
    return render(request,'testapp/adilabad/adilabad1.html')
def Hyderabad_view2(request):
    return render(request,'testapp/hyderabad/hyderabad2.html')
def Warangal_view2(request):
    return render(request,'testapp/warangal/warangal2.html')
def Vijayawada_view2(request):
    return render(request,'testapp/vijaywada/vijayawada2.html')
def Vizag_view2(request):
    return render(request,'testapp/vizag/vizag2.html')
def Adilabad_view2(request):
    return render(request,'testapp/adilabad/adilabad2.html')
def Hyderabad_view3(request):
    return render(request,'testapp/hyderabad/hyderabad3.html')
def Warangal_view3(request):
    return render(request,'testapp/warangal/warangal3.html')
def Vijayawada_view3(request):
    return render(request,'testapp/vijaywada/vijayawada3.html')
def Vizag_view3(request):
    return render(request,'testapp/vizag/vizag3.html')

def index(request):

    return render(request,'testapp/index.html')

def tourist_index(request):
    return render(request,'testapp/tourist_details.html')

def special(request) :
    return HttpResponse("you are logged in,Nice!")

def tourist_logout(request):
    logout(request)
    return render(request,'testapp/index.html')

def guide_logout(request):
    logout(request)
    return render(request,'testapp/index.html')
def Tourist_registration(request):
    registered=False
    if request.method=="POST":
            first_name = request.POST.get('Firstname')
            print(first_name)
            last_name=request.POST.get('Lastname')
            user_name=request.POST.get('Username')
            email_id=request.POST.get('Email')
            pass_word = request.POST.get('Password')
            language=request.POST.get('language')
            gender=request.POST.get('gender')
            age=request.POST.get('age')
            phone_number=request.POST.get('Phonenumber')
            enc_password=make_password(pass_word)
            user=User(username=user_name,password=enc_password)
            user.is_tourist=True
            user.is_guide=False
            user.email=email_id
            try:
                user.save()
                form=Tourist_Registration(first_name=first_name,last_name=last_name,user_name=user_name,email_id=email_id,pass_word=pass_word,language=language,gender=gender,age=age,phone_number=phone_number)
                t=form.save()
            except:
                messages.warning(request, 'username or Email already exists Please Try again with New one')
                return HttpResponseRedirect('testapp/index.html')

            registered = True
            messages.success(request, 'successfully Registered Please Login!')
            return HttpResponseRedirect('testapp/index.html')
    else:
        return render(request,'testapp/index.html')

def Guide_registration(request):
    registered=False
    if request.method=="POST":

        first_name = request.POST.get('Firstname')
        print(first_name)
        last_name = request.POST.get('Lastname')
        user_name = request.POST.get('Username')
        email_id = request.POST.get('Email')
        pass_word = request.POST.get('Password')
        gender = request.POST.get('gender')
        age = request.POST.get('age')
        phone_number = request.POST.get('Phonenumber')
        native_place=request.POST.get('place')
        Address=request.POST.get('address')
        enc_password = make_password(pass_word)
        user = User(username=user_name, password=enc_password)
        user.is_tourist = False
        user.is_guide = True
        user.email=email_id
        try:
            user.save()
            form=Guide_Registration(first_name=first_name,last_name=last_name,user_name=user_name,email_id=email_id,pass_word=pass_word,gender=gender,age=age,phone_number=phone_number,native_place=native_place,Address=Address)
            t=form.save()

        except:
                messages.warning(request,'username or Email already exists Please Try again with new')
                return HttpResponseRedirect("testapp/index.html")
        registered = True
        messages.success(request, 'successfully Registered Please Login to Select the Languages you Known!')
        return HttpResponseRedirect("testapp/index.html")

    else:
       return render(request,'testapp/index.html')



def tourist_login(request):

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)
        if user and user.is_tourist==True:
            if user.is_active:
                login(request,user)
                return render(request,"testapp/tourist_details.html",{'user':user})
            else:
                return render(request,'testapp/index.html')

        else:
            messages.warning(request, 'Invalid credentials!')
            return  HttpResponseRedirect("testapp/index.html")

    else:
        return render(request,'testapp/index.html',{})


def guide_login(request):

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password,is_guide=True,is_tourist=False)
        if user and user.is_guide==True:
            if user.is_active:
                login(request,user)
                return render(request,"testapp/guide_details.html",{'user':user})
            else:
                return render(request,"testapp/index.html")

        else:
            messages.warning(request,'Please Enter Correct details!')
            return HttpResponseRedirect("testapp/index.html")
    else:
        return render(request,'testapp/index.html',{})

def tourist_language_view(request):
    if request.method=='POST':
        #guide_obj=User.objects.get(username=request.user)
        guide_obj = Guide_Registration.objects.get(user_name=request.user)
        #print(guide_obj)
        try:
              check= language_Selection.objects.get(user=guide_obj)
        except:
            check=None
        if check is None:
            ob1=language_Selection(user=guide_obj,languages_select=request.POST.getlist('languages_select'))
            #print(guide_obj,ob1.languages_select)
            #print(request.POST.getlist('languages_select'))
            ob1.save()
        else:
            list_of_lang=check.languages_select
            check.languages_select=request.POST.getlist('languages_select')
            #selection=form.cleaned_data.get('languages_select')
            check.save()
        return render(request,'testapp/guide_details.html')
    else:
        return render(request,'testapp/language_add.html')

def guide_booking_view(request):
    if request.method =='POST':
        date_value=(request.POST.get('date'))
        place_value=request.POST.get('place')
        gender_value = request.POST.get('gender')
        user_value=request.user
        language_value=request.POST.get('language')
        print(date_value,place_value,gender_value,language_value)
        try:
            guide_obj=Guide_Registration.objects.exclude(guide_booking_model__date_field=date_value).filter(native_place=place_value,gender=gender_value)
            query_set_list=[]
            print(guide_obj)
            for query_obj in guide_obj:
                try:
                   p=language_Selection.objects.get(user=query_obj.id)
                   checking=language_value in p.languages_select
                   if(checking==True):
                        query_set_list.append(query_obj)
                except:
                    pass
            print(query_set_list)
            return render(request,'testapp/display_available.html',{'query_set_list':query_set_list,'date_value':date_value})
        except:

            return render(request, 'testapp/display_available.html', {'query_set_list': query_set_list,'date_value':date_value})

    else:
        return render(request,'testapp/guide_book.html')


def display_book_view(request):
    print(request.user)
    guideid = request.GET['id']
    tourist_name=(request.GET['id1'])
    tourist_obj=Tourist_Registration.objects.get(user_name=tourist_name)
    date_value=request.GET['date_value']
    guide_obj=Guide_Registration.objects.get(id=guideid)
    print(guide_obj)
    print(tourist_obj)
    book_obj = Guide_Booking_Model(tourist_username=tourist_obj, guide_username=guide_obj, date_field=date_value)
    book_obj.save()

MiniProject-master/MiniProject-master/TravelGuide/templates/testapp/hyderabad/hyderabad3.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
	<h1 class="text-center">Hyderabad</h1>

<div class="jumbotron">
	<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_HlYZIUxMH-gDMus59NfY_CKx_vvE-tfAN7ZRWik7zeYTH9wxXw">
<div class="Ramoji "><h2>Ramoji Filmcity</h2><p>
A place that is perfect for all the lovers of cinema and Bollywood! Set up by Ramoji Rao, the head of Ramoji group in 1991, Ramoji Film City is a spectacular getaway a little outside the city of Hyderabad. It is spread over 2500 acres and has been certified as the World's largest Film Studio Complex by the Guinness Book of World Records. Ramoji Film City can accommodate 20 film units at one go and has various shooting locations including London Street, Hollywood signage, Japanese gardens, airport, hospital, landscapes and buildings as well as laboratories. Being one of the most popular places to visit in Hyderabad, one can reach Ramoji Film City through a number of packaged tours and buses that leave regularly from the city.

Ramoji Film City is a fun and diverse venue where you can indulge in a number of activities ranging from film city tours to adventure sports and toy train rides to a number of gardens. Smaller renditions of famous monuments in the country such as the Amer Palace are also present here. What's more, you can also stroll through a number of other sets and settings such as royal courts and other locations that have drawn inspiration from different architectures throughout the world. If you decide to visit this destination, after all, be sure to keep aside an entire day for this fun-filled location! </p>
</div>
</div>
<div class="jumbotron">
	<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTszFrFmf_MYJgW9CquyWEIBPGstQtR24Qx9bB-LrAEW_AwuQ_7UQ">
<div class="Salar"><h2>Salar Jung Museum</h2><p> A relic of history on the banks of the Musi River, Salar Jung Museum is located at Darushifa and is one of the crowning jewels of Hyderabad. It is one of the three national museums in the country and also among the largest at 10 Acres and 2 Floors. The most astounding part of going through Salar Jung Museum and its collection is realising that all of the artefacts inside belonged to and were collected by one man alone! The collection inside the museum is owned by Mir Yousuf Ali Khan who was also known as Salar Jung III. With over one million paintings, sculptures, carvings, manuscripts and artefacts, the museum is a repository of art collections a few of which date as far back as the first century. Some of the valuable and rare pieces in the museum are - A painting of Raja Ram Mohan Roy - the artist, Aurangzeb's sword, daggers that belonged to Shah Jahan, Jehangir and a full wardrobe of Tipu Sultan. The museum also has a number of priceless sculptures such as Veiled Rebecca, Double Statue of Mephistopheles & Margaretta and many more. The biggest attraction at the museum is the musical clock that dates back to the 19th century and consists of more than 350 parts.

Salar Jung Museum is the third largest museum in India and is the biggest one-man collection of antiques on the planet. The collection inside the museum was sourced from the Salar Jung Family. The museum is a testament to the passion of Nawab Mir Yusuf Khan for arts and antiques. It also houses an excellent library with more than sixty thousand books and almost eight thousand rare manuscripts.
  </p>
</div>
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="{% url 'testapp:Hyderabad_view2' %}">Previous</a></li>
    <li class="page-item"><a class="page-link" href="{% url 'testapp:Hyderabad_view1' %}">1</a></li>
    <li class="page-item"><a class="page-link" href="{% url 'testapp:Hyderabad_view2' %}">2</a></li>
    <li class="page-item"><a class="page-link" href="{% url 'testapp:Hyderabad_view3' %}">3</a></li>

  </ul>
</nav>

</body>
</html>